### PR TITLE
Added several abbreviations for brackets

### PR DESCRIPTION
**Pull request by traiansf**
I started using your plugin and I find it very useful. While using it,I needed to define some abbreviations for several brackets and I thought others might find them useful (and, also, I would get them for free when I install the plugin on another machine :-) )

### CODE REVIEW

**Comment by arthurxavierx** [comment]
Thanks for the contribution @traiansf!

May I also suggest you trying an alternative plugin I came up with a while ago and uploaded just yesterday: [vim-symbols](https://github.com/arthurxavierx/vim-symbols) uses Vim's user completion machinery to make it easier to visualize and search for symbols. It's still quite a long way from what I envision it to be, but I've found it more comfortable to use than this one.

**Comment by traiansf** [comment]
> May I also suggest you trying an alternative plugin I came up with a while ago and uploaded just yesterday: [vim-symbols](https://github.com/arthurxavierx/vim-symbols) uses Vim's user completion machinery to make it easier to visualize and search for symbols. It's still quite a long way from what I envision it to be, but I've found it more comfortable to use than this one.

@arthurxavierx This sounds really exciting!  However, I must confess that the main reason I landed on the `vim-unicoder` package in the first place was the nice documentation it had (many thanks for that!).

Without documentation, I'm a bit lost on  how this other package should be use and what it offers.  But I promise that I'll give it a try if you provide at least some minimal installation instructions and use cases.

**Comment by arthurxavierx** [comment]
Yes, sorry for that. I will be adding some proper documentation later this week :)

**Comment by arthurxavierx** [comment]
@traiansf you might want to check out [vim-symbols](https://github.com/arthurxavierx/vim-symbols) now as I've improved the documentation and usage by quite a lot since then.

**Pull request merged**
